import type { ActionTier } from "./types.js";

// Every action across all 26 tools classified into a tier
// Based on requirements.md FR-3 table and technical-spec.md D-2
const ACTION_TIERS: Record<string, Record<string, ActionTier>> = {
  accounts: {
    list: "read",
    get: "read",
    create: "write",
    update: "write",
    delete: "destructive",
    list_contacts: "read",
    add_contact: "write",
    remove_contact: "destructive",
  },
  analytics: {
    create_export: "write",
    get_export: "read",
    create_report: "write",
    get_report: "read",
  },
  channels: {
    list: "read",
    get: "read",
    update: "write",
    validate: "read",
    create: "write",
    list_for_teammate: "read",
    list_for_team: "read",
  },
  comments: {
    list: "read",
    get: "read",
    create: "write",
    update: "write",
    list_mentions: "read",
    reply: "write",
  },
  contact_groups: {
    list: "read",
    create: "write",
    delete: "destructive",
    list_contacts: "read",
    add_contacts: "write",
    remove_contacts: "destructive",
  },
  contact_lists: {
    list: "read",
    create: "write",
    delete: "destructive",
    list_contacts: "read",
    add_contacts: "write",
    remove_contacts: "destructive",
  },
  contact_notes: {
    list: "read",
    create: "write",
  },
  contacts: {
    list: "read",
    get: "read",
    create: "write",
    update: "write",
    delete: "destructive",
    merge: "write",
    list_conversations: "read",
    add_handle: "write",
    remove_handle: "destructive",
  },
  conversations: {
    list: "read",
    get: "read",
    search: "read",
    create: "write",
    update: "write",
    delete: "destructive",
    assign: "write",
    list_events: "read",
    list_followers: "read",
    add_followers: "write",
    remove_followers: "destructive",
    list_inboxes: "read",
    add_link: "write",
    remove_links: "destructive",
    list_messages: "read",
    update_reminders: "write",
    add_tag: "write",
    remove_tag: "destructive",
  },
  custom_fields: {
    list_for_accounts: "read",
    list_for_contacts: "read",
    list_for_conversations: "read",
    list_for_inboxes: "read",
    list_for_links: "read",
    list_for_teammates: "read",
  },
  drafts: {
    list: "read",
    create: "write",
    create_reply: "write",
    update: "write",
    delete: "destructive",
  },
  events: {
    list: "read",
    get: "read",
  },
  inboxes: {
    list: "read",
    get: "read",
    create: "write",
    list_channels: "read",
    list_conversations: "read",
    list_access: "read",
    grant_access: "write",
    revoke_access: "destructive",
  },
  knowledge_bases: {
    list: "read",
    get: "read",
    create: "write",
    update: "write",
    list_categories: "read",
    list_articles: "read",
    get_article: "read",
    create_article: "write",
    update_article: "write",
    delete_article: "destructive",
    get_category: "read",
    create_category: "write",
    update_category: "write",
    delete_category: "destructive",
  },
  links: {
    list: "read",
    get: "read",
    create: "write",
    update: "write",
    list_conversations: "read",
  },
  message_template_folders: {
    list: "read",
    get: "read",
    create: "write",
    update: "write",
    delete: "destructive",
    list_children: "read",
    create_child: "write",
  },
  message_templates: {
    list: "read",
    get: "read",
    create: "write",
    update: "write",
    delete: "destructive",
  },
  messages: {
    get: "read",
    create: "write",
    reply: "write",
    import: "write",
    receive_custom: "write",
    get_seen_status: "read",
    mark_seen: "write",
  },
  rules: {
    list: "read",
    get: "read",
    list_for_teammate: "read",
    list_for_team: "read",
  },
  shifts: {
    list: "read",
    get: "read",
    create: "write",
    update: "write",
    list_teammates: "read",
    add_teammates: "write",
    remove_teammates: "destructive",
  },
  signatures: {
    list: "read",
    get: "read",
    update: "write",
    delete: "destructive",
    create_for_teammate: "write",
    create_for_team: "write",
  },
  tags: {
    list: "read",
    get: "read",
    create: "write",
    update: "write",
    delete: "destructive",
    list_children: "read",
    create_child: "write",
    list_conversations: "read",
  },
  teammate_groups: {
    list: "read",
    get: "read",
    create: "write",
    update: "write",
    delete: "destructive",
    list_inboxes: "read",
    add_inboxes: "write",
    remove_inboxes: "destructive",
    list_teammates: "read",
    add_teammates: "write",
    remove_teammates: "destructive",
    list_teams: "read",
    add_teams: "write",
    remove_teams: "destructive",
  },
  teammates: {
    list: "read",
    get: "read",
    update: "write",
    list_conversations: "read",
    list_inboxes: "read",
  },
  teams: {
    list: "read",
    get: "read",
    add_teammates: "write",
    remove_teammates: "destructive",
  },
  token_identity: {
    get: "read",
  },
};

export function getActionTier(tool: string, action: string): ActionTier {
  const toolActions = ACTION_TIERS[tool];
  if (toolActions === undefined) {
    return "write"; // unknown tool defaults to write (safe default)
  }
  const tier = toolActions[action];
  if (tier === undefined) {
    return "write"; // unknown action defaults to write (safe default)
  }
  return tier;
}

export function getAllActionTiers(): Record<string, Record<string, ActionTier>> {
  return ACTION_TIERS;
}
